version: '3.8'

services:
  ctyun-auto:
    # 从 GitHub Container Registry 拉取镜像
    image: ghcr.io/wanyishao/ctyun-auto:latest
    container_name: ctyun_auto
    restart: on-failure
    volumes:
      - ./data:/app/data
    extra_hosts:
      - "deskcdn.ctyun.cn:106.120.187.154"
      - "deskcdn.ctyun.cn.ctadns.cn:106.120.187.154"
    environment:
      - APP_USER=你的账号
      - APP_PASSWORD=你的密码
      - CRON_LOGIN=0 3,20 * * *
      - CRON_PC=0 4,6 * * *
      - INIT_RUN=false
